"""empty message

Revision ID: 3a0a41f0ca45
Revises: 0eed5d06290d
Create Date: 2024-11-17 01:03:11.641780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0a41f0ca45'
down_revision = '0eed5d06290d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('repair', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.Boolean(), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('repair')
        batch_op.drop_column('parking')

    # ### end Alembic commands ###
