"""empty message

Revision ID: 5c221c44ce59
Revises: 654a3b0fbed7
Create Date: 2024-11-16 22:15:19.788798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c221c44ce59'
down_revision = '654a3b0fbed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('repair', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.Boolean(), nullable=True))
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('place', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('repair')
        batch_op.drop_column('parking')

    # ### end Alembic commands ###
